export const MANIPULATION_LIST = [
  "Sensationalism",
  "Misleading headlines",
  "Quoting out of context",
  "Cherry-picking data",
  "Omission of key information",
  "Biased language",
  "Logical fallacies",
  "Unbalanced reporting",
  "Selective use of sources",
  "Unsubstantiated claims",
  "Appeal to authority",
  "False equivalence",
  "Confirmation bias",
  "Filter bubbles",
  "Echo chambers",
  "Misattribution",
  "Clickbait",
  "Manufactured controversy",
  "Distortion of facts",
  "Conflating correlation with causation",
  "Oversimplification",
  "Ad hominem attacks",
  "Anonymous sources",
  "Straw man argument",
  "Slippery slope",
  "Appeal to emotion",
  "Hasty generalization",
  "Circular reasoning",
  "Post hoc fallacy",
  "False analogy",
  "Tu quoque",
  "Bandwagon effect",
  "Red herring",
  "The availability heuristic",
  "The representativeness heuristic",
  "The anchoring effect",
  "The halo effect",
  "The horn effect",
  "The Dunning-Kruger effect",
  "The backfire effect",
  "The illusory truth effect",
  "The mere exposure effect",
  "The bystander effect",
  "The authority bias",
  "The contrast effect",
  "The sunk cost fallacy",
  "The planning fallacy",
  "The actor-observer bias",
  "The fundamental attribution error",
  "Groupthink",
  "The self-fulfilling prophecy",
  "The priming effect",
  "The decoy effect",
  "The scarcity principle",
  "The reciprocity principle",
  "The commitment and consistency principle",
  "The liking principle",
  "Social proof",
  "The law of triviality",
  "The clustering illusion",
  "The self-handicapping bias",
  "The overconfidence effect",
  "The projection bias",
  "Optimism bias",
  "The Zeigarnik effect",
  "The endowment effect",
  "The gambler's fallacy",
  "The hot-hand fallacy",
  "In-group bias",
  "The availability cascade",
  "The framing effect",
  "The anchoring-and-adjustment heuristic",
  "The curse of knowledge",
  "The illusion of control",
  "The self-serving bias",
  "The bystander apathy effect",
  "The illusion of transparency",
  "The spotlight effect",
  "The just-world hypothesis",
  "False dilemma",
  "Fear of missing out (FOMO)",
  "The placebo effect",
  "The boomerang effect",
  "The primacy effect",
  "The recency effect",
  "The serial position effect",
  "The narrative fallacy",
  "The affect heuristic",
  "The base rate fallacy",
  "The gambler's fallacy",
  "The hot-hand fallacy",
  "The illusion of validity",
  "The peak-end rule",
  "The pseudocertainty effect",
  "The conjunction fallacy",
  "The disconfirmation bias",
  "The false consensus effect",
  "The hindsight bias",
  "The impact bias",
  "The optimism bias",
];

