export const BASE_URL = 'https://honestymeter.com';
export const PAGE_ABSOLUTE_URL = {
  ABOUT: `${BASE_URL}/about`,
  TERMS: `${BASE_URL}/terms`,
};
export const EMAIL_ADDRESS = 'info@honestymeter.com';
export const PAGE_LABELS_MAP = {
  home: 'Home',
  about: 'About',
  terms: 'Terms and conditions',
};
export const PAGE_LABELS = ['Home', 'People', 'About', 'Terms'];
export const PAGE_ROUTES = ['/', 'people', 'about', 'terms'];
export const PAGE_URL_TO_INDEX_MAP = {
  '/': 0,
  '/people': 1,
  '/people/[name]': 1,
  '/report/[reportId]': -1,
  '/about': 2,
  '/terms': 3,
};
export const EMPTY_STRING = '';
export const SPACE = ' ';
export const PAYPAL_DONATE_URL =
  'https://www.paypal.com/donate/?hosted_button_id=2K88Y2UF99YRU';
export const GITHUB_URL = 'https://github.com/BetterForAll/HonestyMeter';
export const WOLRD_NEWS_API_URL = 'https://worldnewsapi.com';

export const EVENT = {
  reportRequested: 'Report requested',
  reportReceived: 'Report received',
  reportParsed: 'Report parsed',
  reportError: 'Report error',
  reportCopied: 'Report copied',
  reportCopyError: 'Report copy error',
  shareApp: (platform) => `Share app on ${platform}`,
  shareReport: (platform) => `Share report on ${platform}`,
  sharedReportViewed: 'Shared report viewed',
  pageLoaded: 'Page loaded',
  peoplePageLoaded: 'People page loaded',
  personPageLoaded: (name) => 'Person page loaded',
  generateNewReportClicked: 'Generate New Report Clicked',
  cancelNewReportClicked: 'Cancel New Report Clicked',
  reportCardClicked: 'Report Card Clicked',
  viewReportClicked: 'View Report Clicked',
  closeReportClicked: 'Close Report Clicked',
  nextPageClicked: 'Next Page Clicked',
  previousPageClicked: 'Previous Page Clicked',
  skipToFirstPageClicked: 'Skip To First Page Clicked',
  articleLinkClicked: 'Article Link Clicked',
  reportViewed: 'Report Viewed',
  personClicked: 'Person Clicked',
  searchClickedPeoplePage: 'Search Clicked - People',
  searchClickedHomePage: 'Search Clicked - Home Page',

};

export const API_URL = {
  GENERATE_REPORT: './api/report',
  SAVED_REPORT: './api/saved_report',
};

export const STEPS = {
  forward: 1,
  back: -1,
};

export const CATEGORIES = [
  'top',
  'world',
  'politics',
  'business',
  'entertainment',
  'environment',
  'food',
  'health',
  'science',
  'sports',
  'technology',
  'tourism',
];

const countries = [
  { country: 'Afghanistan', code: 'af' },
  { country: 'Albania', code: 'al' },
  { country: 'Algeria', code: 'dz' },
  { country: 'Angola', code: 'ao' },
  { country: 'Argentina', code: 'ar' },
  { country: 'Australia', code: 'au' },
  { country: 'Austria', code: 'at' },
  { country: 'Azerbaijan', code: 'az' },
  { country: 'Bahrain', code: 'bh' },
  { country: 'Bangladesh', code: 'bd' },
  { country: 'Barbados', code: 'bb' },
  { country: 'Belarus', code: 'by' },
  { country: 'Belgium', code: 'be' },
  { country: 'Bermuda', code: 'bm' },
  { country: 'Bhutan', code: 'bt' },
  { country: 'Bolivia', code: 'bo' },
  { country: 'Bosnia And Herzegovina', code: 'ba' },
  { country: 'Brazil', code: 'br' },
  { country: 'Brunei', code: 'bn' },
  { country: 'Bulgaria', code: 'bg' },
  { country: 'Burkina fasco', code: 'bf' },
  { country: 'Cambodia', code: 'kh' },
  { country: 'Cameroon', code: 'cm' },
  { country: 'Canada', code: 'ca' },
  { country: 'Cape Verde', code: 'cv' },
  { country: 'Cayman Islands', code: 'ky' },
  { country: 'Chile', code: 'cl' },
  { country: 'China', code: 'cn' },
  { country: 'Colombia', code: 'co' },
  { country: 'Comoros', code: 'km' },
  { country: 'Costa Rica', code: 'cr' },
  { country: 'Côte d\'Ivoire', code: 'ci' },
  { country: 'Croatia', code: 'hr' },
  { country: 'Cuba', code: 'cu' },
  { country: 'Cyprus', code: 'cy' },
  { country: 'Czech republic', code: 'cz' },
  { country: 'Denmark', code: 'dk' },
  { country: 'Djibouti', code: 'dj' },
  { country: 'Dominica', code: 'dm' },
  { country: 'Dominican republic', code: 'do' },
  { country: 'DR Congo', code: 'cd' },
  { country: 'Ecuador', code: 'ec' },
  { country: 'Egypt', code: 'eg' },
  { country: 'El Salvador', code: 'sv' },
  { country: 'Estonia', code: 'ee' },
  { country: 'Ethiopia', code: 'et' },
  { country: 'Fiji', code: 'fj' },
  { country: 'Finland', code: 'fi' },
  { country: 'France', code: 'fr' },
  { country: 'French polynesia', code: 'pf' },
  { country: 'Gabon', code: 'ga' },
  { country: 'Georgia', code: 'ge' },
  { country: 'Germany', code: 'de' },
  { country: 'Ghana', code: 'gh' },
  { country: 'Greece', code: 'gr' },
  { country: 'Guatemala', code: 'gt' },
  { country: 'Guinea', code: 'gn' },
  { country: 'Haiti', code: 'ht' },
  { country: 'Honduras', code: 'hn' },
  { country: 'Hong kong', code: 'hk' },
  { country: 'Hungary', code: 'hu' },
  { country: 'Iceland', code: 'is' },
  { country: 'India', code: 'in' },
  { country: 'Indonesia', code: 'id' },
  { country: 'Iraq', code: 'iq' },
  { country: 'Ireland', code: 'ie' },
  { country: 'Israel', code: 'il' },
  { country: 'Italy', code: 'it' },
  { country: 'Jamaica', code: 'jm' },
  { country: 'Japan', code: 'jp' },
  { country: 'Jordan', code: 'jo' },
  { country: 'Kazakhstan', code: 'kz' },
  { country: 'Kenya', code: 'ke' },
  { country: 'Kuwait', code: 'kw' },
  { country: 'Kyrgyzstan', code: 'kg' },
  { country: 'Latvia', code: 'lv' },
  { country: 'Lebanon', code: 'lb' },
  { country: 'Libya', code: 'ly' },
  { country: 'Lithuania', code: 'lt' },
  { country: 'Luxembourg', code: 'lu' },
  { country: 'Macau', code: 'mo' },
  { country: 'Macedonia', code: 'mk' },
  { country: 'Madagascar', code: 'mg' },
  { country: 'Malawi', code: 'mw' },
  { country: 'Malaysia', code: 'my' },
  { country: 'Maldives', code: 'mv' },
  { country: 'Mali', code: 'ml' },
  { country: 'Malta', code: 'mt' },
  { country: 'Mauritania', code: 'mr' },
  { country: 'Mexico', code: 'mx' },
  { country: 'Moldova', code: 'md' },
  { country: 'Mongolia', code: 'mn' },
  { country: 'Montenegro', code: 'me' },
  { country: 'Morocco', code: 'ma' },
  { country: 'Mozambique', code: 'mz' },
  { country: 'Myanmar', code: 'mm' },
  { country: 'Namibia', code: 'na' },
  { country: 'Nepal', code: 'np' },
  { country: 'Netherland', code: 'nl' },
  { country: 'New zealand', code: 'nz' },
  { country: 'Niger', code: 'ne' },
  { country: 'Nigeria', code: 'ng' },
  { country: 'North korea', code: 'kp' },
  { country: 'Norway', code: 'no' },
  { country: 'Oman', code: 'om' },
  { country: 'Pakistan', code: 'pk' },
  { country: 'Panama', code: 'pa' },
  { country: 'Paraguay', code: 'py' },
  { country: 'Peru', code: 'pe' },
  { country: 'Philippines', code: 'ph' },
  { country: 'Poland', code: 'pl' },
  { country: 'Portugal', code: 'pt' },
  { country: 'Puerto rico', code: 'pr' },
  { country: 'Romania', code: 'ro' },
  { country: 'Russia', code: 'ru' },
  { country: 'Rwanda', code: 'rw' },
  { country: 'Samoa', code: 'ws' },
  { country: 'San Marino', code: 'sm' },
  { country: 'Saudi arabia', code: 'sa' },
  { country: 'Senegal', code: 'sn' },
  { country: 'Serbia', code: 'rs' },
  { country: 'Singapore', code: 'sg' },
  { country: 'Slovakia', code: 'sk' },
  { country: 'Slovenia', code: 'si' },
  { country: 'Solomon Islands', code: 'sb' },
  { country: 'Somalia', code: 'so' },
  { country: 'South africa', code: 'za' },
  { country: 'South korea', code: 'kr' },
  { country: 'Spain', code: 'es' },
  { country: 'Sri Lanka', code: 'lk' },
  { country: 'Sudan', code: 'sd' },
  { country: 'Sweden', code: 'se' },
  { country: 'Switzerland', code: 'ch' },
  { country: 'Syria', code: 'sy' },
  { country: 'Taiwan', code: 'tw' },
  { country: 'Tajikistan', code: 'tj' },
  { country: 'Tanzania', code: 'tz' },
  { country: 'Thailand', code: 'th' },
  { country: 'Tonga', code: 'to' },
  { country: 'Tunisia', code: 'tn' },
  { country: 'Turkey', code: 'tr' },
  { country: 'Turkmenistan', code: 'tm' },
  { country: 'Uganda', code: 'ug' },
  { country: 'Ukraine', code: 'ua' },
  { country: 'United arab emirates', code: 'ae' },
  { country: 'United kingdom', code: 'gb' },
  { country: 'United states of america', code: 'us' },
  { country: 'Uruguay', code: 'uy' },
  { country: 'Uzbekistan', code: 'uz' },
  { country: 'Venezuela', code: 've' },
  { country: 'Vietnam', code: 'vi' },
  { country: 'Yemen', code: 'ye' },
  { country: 'Zambia', code: 'zm' },
  { country: 'Zimbabwe', code: 'zw' }
];

